"""create initial tables

Revision ID: 561f0b46d411
Revises:
Create Date: 2026-05-04 01:32:33.829631

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "561f0b46d411"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("nama_admin", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("kata_sandi", sa.String(length=255), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_email"), "admin", ["email"], unique=True)
    op.create_table(
        "kategori",
        sa.Column("nama_kategori", sa.String(length=100), nullable=False),
        sa.Column("deskripsi", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metode_pembayaran",
        sa.Column("nama_metode", sa.String(length=100), nullable=False),
        sa.Column("tipe_metode", sa.String(length=30), nullable=False),
        sa.Column("nama_bank", sa.String(length=100), nullable=True),
        sa.Column("nomor_rekening", sa.String(length=50), nullable=True),
        sa.Column("nama_pemilik_rekening", sa.String(length=100), nullable=True),
        sa.Column("gambar_qr", sa.String(length=255), nullable=True),
        sa.Column("status_aktif", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metode_pembayaran_status_aktif"),
        "metode_pembayaran",
        ["status_aktif"],
        unique=False,
    )
    op.create_table(
        "pelanggan",
        sa.Column("nama_pelanggan", sa.String(length=100), nullable=False),
        sa.Column("no_telepon", sa.String(length=20), nullable=False),
        sa.Column("alamat", sa.Text(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pelanggan_no_telepon"), "pelanggan", ["no_telepon"], unique=False)
    op.create_table(
        "pesanan",
        sa.Column(
            "pelanggan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "metode_pembayaran_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("kode_pesanan", sa.String(length=50), nullable=False),
        sa.Column("tanggal_pesanan", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_harga", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("nama_pelanggan", sa.String(length=100), nullable=False),
        sa.Column("no_telepon_pelanggan", sa.String(length=20), nullable=False),
        sa.Column("alamat_pelanggan", sa.Text(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("status_pembayaran", sa.String(length=30), nullable=False),
        sa.Column("status_pesanan", sa.String(length=30), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["metode_pembayaran_id"],
            ["metode_pembayaran.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pelanggan_id"], ["pelanggan.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lacak_pesanan", "pesanan", ["kode_pesanan", "no_telepon_pelanggan"], unique=False
    )
    op.create_index("idx_pesanan_status_pembayaran", "pesanan", ["status_pembayaran"], unique=False)
    op.create_index("idx_pesanan_status_pesanan", "pesanan", ["status_pesanan"], unique=False)
    op.create_index("idx_pesanan_tanggal", "pesanan", ["tanggal_pesanan"], unique=False)
    op.create_index(op.f("ix_pesanan_kode_pesanan"), "pesanan", ["kode_pesanan"], unique=True)
    op.create_index(
        op.f("ix_pesanan_metode_pembayaran_id"), "pesanan", ["metode_pembayaran_id"], unique=False
    )
    op.create_index(
        op.f("ix_pesanan_no_telepon_pelanggan"), "pesanan", ["no_telepon_pelanggan"], unique=False
    )
    op.create_index(op.f("ix_pesanan_pelanggan_id"), "pesanan", ["pelanggan_id"], unique=False)
    op.create_index(
        op.f("ix_pesanan_status_pembayaran"), "pesanan", ["status_pembayaran"], unique=False
    )
    op.create_index(op.f("ix_pesanan_status_pesanan"), "pesanan", ["status_pesanan"], unique=False)
    op.create_table(
        "produk",
        sa.Column(
            "kategori_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("nama_produk", sa.String(length=150), nullable=False),
        sa.Column("deskripsi", sa.Text(), nullable=True),
        sa.Column("harga", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stok", sa.Integer(), nullable=False),
        sa.Column("gambar", sa.String(length=255), nullable=True),
        sa.Column("status_tersedia", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["kategori_id"], ["kategori.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_produk_kategori_id", "produk", ["kategori_id"], unique=False)
    op.create_index("idx_produk_status_tersedia", "produk", ["status_tersedia"], unique=False)
    op.create_index(op.f("ix_produk_kategori_id"), "produk", ["kategori_id"], unique=False)
    op.create_index(op.f("ix_produk_status_tersedia"), "produk", ["status_tersedia"], unique=False)
    op.create_table(
        "bukti_pembayaran",
        sa.Column(
            "pesanan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("nama_file", sa.String(length=255), nullable=False),
        sa.Column("path_file", sa.String(length=255), nullable=False),
        sa.Column("diunggah_pada", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pesanan_id"], ["pesanan.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bukti_pembayaran_pesanan_id", "bukti_pembayaran", ["pesanan_id"], unique=False
    )
    op.create_index(
        op.f("ix_bukti_pembayaran_pesanan_id"), "bukti_pembayaran", ["pesanan_id"], unique=False
    )
    op.create_table(
        "detail_pesanan",
        sa.Column(
            "pesanan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "produk_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("nama_produk", sa.String(length=150), nullable=False),
        sa.Column("harga_produk", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("jumlah", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pesanan_id"], ["pesanan.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["produk_id"], ["produk.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_detail_pesanan_pesanan_id", "detail_pesanan", ["pesanan_id"], unique=False)
    op.create_index("idx_detail_pesanan_produk_id", "detail_pesanan", ["produk_id"], unique=False)
    op.create_index(
        op.f("ix_detail_pesanan_pesanan_id"), "detail_pesanan", ["pesanan_id"], unique=False
    )
    op.create_index(
        op.f("ix_detail_pesanan_produk_id"), "detail_pesanan", ["produk_id"], unique=False
    )
    op.create_table(
        "riwayat_stok",
        sa.Column(
            "produk_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("admin_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("jenis_perubahan", sa.String(length=30), nullable=False),
        sa.Column("stok_sebelum", sa.Integer(), nullable=False),
        sa.Column("jumlah_perubahan", sa.Integer(), nullable=False),
        sa.Column("stok_sesudah", sa.Integer(), nullable=False),
        sa.Column("keterangan", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diperbarui_pada", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["produk_id"], ["produk.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_riwayat_stok_admin_id", "riwayat_stok", ["admin_id"], unique=False)
    op.create_index("idx_riwayat_stok_produk_id", "riwayat_stok", ["produk_id"], unique=False)
    op.create_index(op.f("ix_riwayat_stok_admin_id"), "riwayat_stok", ["admin_id"], unique=False)
    op.create_index(op.f("ix_riwayat_stok_produk_id"), "riwayat_stok", ["produk_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_riwayat_stok_produk_id"), table_name="riwayat_stok")
    op.drop_index(op.f("ix_riwayat_stok_admin_id"), table_name="riwayat_stok")
    op.drop_index("idx_riwayat_stok_produk_id", table_name="riwayat_stok")
    op.drop_index("idx_riwayat_stok_admin_id", table_name="riwayat_stok")
    op.drop_table("riwayat_stok")
    op.drop_index(op.f("ix_detail_pesanan_produk_id"), table_name="detail_pesanan")
    op.drop_index(op.f("ix_detail_pesanan_pesanan_id"), table_name="detail_pesanan")
    op.drop_index("idx_detail_pesanan_produk_id", table_name="detail_pesanan")
    op.drop_index("idx_detail_pesanan_pesanan_id", table_name="detail_pesanan")
    op.drop_table("detail_pesanan")
    op.drop_index(op.f("ix_bukti_pembayaran_pesanan_id"), table_name="bukti_pembayaran")
    op.drop_index("idx_bukti_pembayaran_pesanan_id", table_name="bukti_pembayaran")
    op.drop_table("bukti_pembayaran")
    op.drop_index(op.f("ix_produk_status_tersedia"), table_name="produk")
    op.drop_index(op.f("ix_produk_kategori_id"), table_name="produk")
    op.drop_index("idx_produk_status_tersedia", table_name="produk")
    op.drop_index("idx_produk_kategori_id", table_name="produk")
    op.drop_table("produk")
    op.drop_index(op.f("ix_pesanan_status_pesanan"), table_name="pesanan")
    op.drop_index(op.f("ix_pesanan_status_pembayaran"), table_name="pesanan")
    op.drop_index(op.f("ix_pesanan_pelanggan_id"), table_name="pesanan")
    op.drop_index(op.f("ix_pesanan_no_telepon_pelanggan"), table_name="pesanan")
    op.drop_index(op.f("ix_pesanan_metode_pembayaran_id"), table_name="pesanan")
    op.drop_index(op.f("ix_pesanan_kode_pesanan"), table_name="pesanan")
    op.drop_index("idx_pesanan_tanggal", table_name="pesanan")
    op.drop_index("idx_pesanan_status_pesanan", table_name="pesanan")
    op.drop_index("idx_pesanan_status_pembayaran", table_name="pesanan")
    op.drop_index("idx_lacak_pesanan", table_name="pesanan")
    op.drop_table("pesanan")
    op.drop_index(op.f("ix_pelanggan_no_telepon"), table_name="pelanggan")
    op.drop_table("pelanggan")
    op.drop_index(op.f("ix_metode_pembayaran_status_aktif"), table_name="metode_pembayaran")
    op.drop_table("metode_pembayaran")
    op.drop_table("kategori")
    op.drop_index(op.f("ix_admin_email"), table_name="admin")
    op.drop_table("admin")
    # ### end Alembic commands ###
